### ISSUE TITLE
Crash on iPhone 5, and 5 SC

### ISSUE THREAD

**Issue by IrfanMarwat** [cashwalk/ScratchImage#3]
Crashes on iPhone 5, when start scratching..

**Comment by atif-khan** [comment]
Facing the same problem. Crashes in iPhone 5 and SE. Please resolve ASAP.

**Comment by k-lpmg** [comment]
Hi @IrfanMarwat @atif-khan 

Thank you for uploading this issue.
I tried to reproduce the issue and found a crash site.

Crashing point is here.
https://github.com/cashwalk/ScratchImage/blob/f85ac1f2ee3266207c76f18697cb16b66fc9bde5/Sources/ScratchImage/UIView-Extensions.swift#L35
This issue is reproduced when the width of ScratchImageView is over 300 in iPhone5 series.

**Comment by k-lpmg** [comment]
I have released ScratchImage 1.1.1 that temporarily fix crash.

However, the iPhone 5 size series does not have the ability to check for duplicate scratches.
I will try fix it soon.

To summarize, use ScratchImage 1.1.1 to solve this issue, or do not make ScratchImageView widths over 300 in iPhone5 series.

Thanks!
